# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='dietician',
            old_name='type',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='type',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
