# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170806_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testiment_name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
