# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=10000000)),
            ],
        ),
    ]
