# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='package1_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical stuff (to be used by developers'),
        ),
        migrations.AddField(
            model_name='banner',
            name='package2_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical stuff (to be used by developers'),
        ),
        migrations.AddField(
            model_name='banner',
            name='package3_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical stuff (to be used by developers'),
        ),
        migrations.AddField(
            model_name='banner',
            name='package4_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical stuff (to be used by developers'),
        ),
    ]
