# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='package1_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='package2_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='package3_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='package4_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
