# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20170806_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('mobile', models.IntegerField(verbose_name='Mobile Number')),
                ('alternate_mobile', models.IntegerField(verbose_name='Alternate Mobile Number')),
                ('email_id', models.CharField(max_length=1000, verbose_name='Email')),
                ('goals', models.CharField(max_length=1000, verbose_name='Personal/Family Goals')),
                ('height', models.IntegerField(verbose_name='Height (cms)')),
                ('weight', models.IntegerField(verbose_name='Weight (kg)')),
                ('blood', models.CharField(choices=[('A+', 'A positive'), ('B+', 'B positive'), ('AB+', 'AB positive'), ('O+', 'O positive'), ('A-', 'A negative'), ('B-', 'B negative'), ('AB-', 'AB negative'), ('O-', 'O negative')], max_length=3, verbose_name='Blood Group')),
                ('pressure', models.CharField(max_length=10, verbose_name='Blood Pressure (value1/value2) E.g. 120/80')),
                ('bmi', models.CharField(max_length=100, verbose_name='Body Mass Index (Leave Blank if unknown)')),
                ('client_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
    ]
