# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='alcohol',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='How frequently do you consume alcohol'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='allergic_food',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Allergic Foods'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='breakfast',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Breakfast (First meal of the day)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='brunch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cul_back',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Provide details of Cultural Background'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cupboard',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='What foods would I always find in your refrigiator?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='diet_pref',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Diet Preference'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='dinner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='dislike_food',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foods Disliked'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='evening_snacks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evening High Tea and Snacks'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='fav_food',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Favorite Foods'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='fav_fruit',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Favorite Fruits'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='food_consumed',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Please provide details of food type consumed'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='home_cooked',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='What percent fo your food is home cooked (rate from 0 to 1)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='illness',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Provide details of Medical Illness/Condition (if any)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='illness_family',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Details of any illness of family (if any)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='lunch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nutritional_panels',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Do you need nutritional panels?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='off_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Off Days'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='on_waking',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='On waking up (eg. A glass of milk)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='out_cooked',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='How often you eat outside food in a week?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='reg_back',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Location details in country'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='school_timings',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='School Timings'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sleed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sleep'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='smoke',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='How frequently do you smoke'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='supper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='supplements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Supplement Details (if any)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='surgery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Your Surgery Details, if any'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tobacco',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='How frequently do you consume tobacco based mouth freshners'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='training_evening',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Evening Training Timing'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='training_morning',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Morning Training Timing'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='wake_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Wake Up'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='blood',
            field=models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], max_length=3, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='bmi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Body Mass Index (Leave Blank if unknown)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='email_id',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
