# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='client_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Client Username'),
        ),
    ]
